[package]
name = "starchain-identity"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.47.0"

[dev-dependencies]
multiversx-sc-scenario = "0.47.0"

[workspace]
members = ["."] 